/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.platform.bug;

import org.apache.commons.lang3.StringUtils;

public class Library {
    public boolean someLibraryMethod() {
        StringUtils.chop("abc");
        return true;
    }
}
